INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (1, 'KAB. ACEH SELATAN\n', 1);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (2, 'KAB. ACEH TENGGARA\n', 1);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (3, 'KAB. ACEH TIMUR\n', 1);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (4, 'KAB. TENGAH *)\n', 1);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (5, 'KAB. ACEH BARAT\n', 1);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (6, 'KAB. ACEH BESAR\n', 1);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (7, 'KAB. PIDIE\n', 1);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (8, 'KAB. ACEH UTARA\n', 1);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (9, 'KAB. SIMEULUE\n', 1);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (10, 'KAB. ACEH SINGKIL\n', 1);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (11, 'KAB. BIREUN\n', 1);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (12, 'KAB. ACEH BARAT DAYA\n', 1);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (13, 'KAB. GAYO LUES\n', 1);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (14, 'KAB. ACEH JAYA\n', 1);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (15, 'KAB. NAGAN JAYA\n', 1);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (16, 'KAB. ACEH TAMIANG\n', 1);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (17, 'KAB. BENER MERIAH*)\n', 1);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (18, 'KOTA BANDA ACEH\n', 1);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (19, 'KOTA SABANG\n', 1);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (20, 'KOTA LHOKSEUMAWE\n', 1);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (21, 'KOTA LANGSA\n', 1);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (22, 'KAB. TAPANULI TENGAH\n', 2);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (23, 'KAB. TAPANULI UTARA\n', 2);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (24, 'KAB. TAPANULI SELATAN\n', 2);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (25, 'KAB. NIAS\n', 2);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (26, 'KAB. LANGKAT\n', 2);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (27, 'KAB. KARO\n', 2);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (28, 'KAB. DELI SERDANG\n', 2);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (29, 'KAB. SIMALUNGUN\n', 2);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (30, 'KAB. ASAHAN\n', 2);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (31, 'KAB. LABUHAN BATU\n', 2);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (32, 'KAB. DAIRI\n', 2);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (33, 'KAB. TOBA SAMOSIR\n', 2);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (34, 'KAB. MANDAILING NATAL\n', 2);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (35, 'KAB. NIAS SELATAN\n', 2);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (36, 'KAB. PAKPAK BARAT\n', 2);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (37, 'KAB. HUMBANG HASUNDUTAN\n', 2);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (38, 'KAB. SAMOSIR *)\n', 2);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (39, 'KAB. SERDANG BEDAGAI *)\n', 2);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (40, 'KOTA MEDAN\n', 2);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (41, 'KOTA PEMATANG SIANTAR\n', 2);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (42, 'KOTA SIBOLGA\n', 2);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (43, 'KOTA TANJUNG BALAI\n', 2);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (44, 'KOTA BINJAI\n', 2);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (45, 'KOTA TEBING TINGGI\n', 2);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (46, 'KOTA PADANG SIDEMPUAN\n', 2);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (47, 'KAB.PESISIR SELATAN\n', 3);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (48, 'KAB. SOLOK*)\n', 3);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (49, 'KAB. SW.LUNTO\n', 3);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (50, 'KAB. TANAH DATAR\n', 3);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (51, 'KAB. PADANG PARIAMAN\n', 3);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (52, 'KAB. AGAM\n', 3);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (53, 'KAB. LIMA PULUH KOTA\n', 3);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (54, 'KAB. PASAMAN *)\n', 3);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (55, 'KAB. KEPULAUAN MENTAWAI\n', 3);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (56, 'KAB. DHARMASRAYA*)\n', 3);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (57, 'KAB. SOLOK SELATAN *)\n', 3);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (58, 'KAB. PASAMAN BARAT *)\n', 3);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (59, 'KOTA PADANG\n', 3);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (60, 'KOTA SOLOK\n', 3);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (61, 'KOTA SAWHLUNTO\n', 3);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (62, 'KOTA PADANG PANJANG\n', 3);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (63, 'KOTA BUKITTINGGI\n', 3);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (64, 'KOTA PAYAKUMBUH\n', 3);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (65, 'KOTA PARIAMAN\n', 3);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (66, 'KAB. KAMPAR\n', 4);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (67, 'KAB. INDRAGIRI HULU\n', 4);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (68, 'KAB. BENGKALIS\n', 4);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (69, 'KAB. INDRAGIRI HILIR\n', 4);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (70, 'KAB. PELALAWAN\n', 4);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (71, 'KAB. ROKAN HULU\n', 4);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (72, 'KAB. ROKAN HILIR\n', 4);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (73, 'KAB. SIAK\n', 4);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (74, 'KAB. KUANTAN SINGINGI\n', 4);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (75, 'KOTA PEKAN BARU\n', 4);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (76, 'KOTA DUMAI\n', 4);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (77, 'KAB. KERINCI\n', 5);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (78, 'KAB. MEANGIN\n', 5);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (79, 'KAB. SAROLANGUN\n', 5);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (80, 'KAB. BATANGHARI\n', 5);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (81, 'KAB. MUARO JAMBI\n', 5);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (82, 'KAB. TANJUNG JABUNG BARAT', 5);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (83, 'KAB. TANJUNG JABUNG TIMUR', 5);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (84, 'KAB. BUNGO\n', 5);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (85, 'KAB. TEBO\n', 5);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (86, 'KOTA JAMBI\n', 5);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (87, 'KAB. OGAN KOMERING ULU *)', 6);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (88, 'KAB. OGAN KOMERING ILIR *', 6);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (89, 'KAB. MUARA ENIM\n', 6);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (90, 'KAB. LAHAT\n', 6);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (91, 'KAB. MUSI RAWAS\n', 6);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (92, 'KAB. MUSI BANYUASIN\n', 6);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (93, 'KAB. BANYUASIN\n', 6);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (94, 'KAB. OKU TIMUR *)\n', 6);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (95, 'KAB. OKU SELATAN *)\n', 6);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (96, 'KAB. OGAN ILIR *)\n', 6);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (97, 'KOTA PALEMBANG\n', 6);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (98, 'KOTA PAGAR ALAM\n', 6);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (99, 'KOTA LUBUK LINGGAU\n', 6);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (100, 'KOTA PRABUMULIH\n', 6);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (101, 'KAB. BENGKULU SELATAN\n', 7);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (102, 'KAB. REJANG LEBONG *)\n', 7);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (103, 'KAB. BENGKULU UTARA\n', 7);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (104, 'KAB. KAUR\n', 7);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (105, 'KAB. SELUMA\n', 7);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (106, 'KAB. MUKO MUKO\n', 7);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (107, 'KAB. LEBONG *)\n', 7);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (108, 'KAB. KEPAHIANG *)\n', 7);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (109, 'KOTA BENGKULU\n', 7);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (110, 'KAB. LAMPUNG SELATAN\n', 8);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (111, 'KAB. LAMPUNG TENGAH\n', 8);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (112, 'KAB. LAMPUNG UTARA\n', 8);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (113, 'KAB. LAMPUNG BARAT\n', 8);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (114, 'KAB. TULANG BAWANG\n', 8);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (115, 'KAB. TANGGAMUS\n', 8);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (116, 'KAB. LAMPUNG TIMUR\n', 8);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (117, 'KAB. WAY KANAN\n', 8);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (118, 'KOTA BANDAR LAMPUNG\n', 8);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (119, 'KOTA METRO\n', 8);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (120, 'KAB. BANGKA\n', 9);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (121, 'KAB. BELITUNG\n', 9);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (122, 'KAB. BANGKA SELATAN\n', 9);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (123, 'KAB. BANGKA TENGAH\n', 9);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (124, 'KAB. BANGKA BARAT\n', 9);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (125, 'KAB. BANGKA TIMUR\n', 9);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (126, 'KOTA PANGKAL PINANG\n', 9);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (127, 'KAB. KEPULAUAN RIAU *)\n', 10);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (128, 'KAB. KARIMUN\n', 10);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (129, 'KAB. NATUNA\n', 10);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (130, 'KAB. LINGGA *)\n', 10);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (131, 'KOTA BATAM\n', 10);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (132, 'KOTA TANJUNG PINANG\n', 10);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (133, 'KAB.ADM.KEP.SERIBU***)\n', 11);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (134, 'KODYA JAKARTA PUSAT***)\n', 11);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (135, 'KODYA JAKARTA UTARA***)\n', 11);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (136, 'KODYA JAKARTA BARAT***)\n', 11);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (137, 'KODYA JAKARTA SELATAN***)', 11);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (138, 'KODYA JAKARTA TIMUR***)\n', 11);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (139, 'KAB. BOGOR\n', 12);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (140, 'KAB. SUKABUMI\n', 12);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (141, 'KAB. CIANJUR\n', 12);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (142, 'KAB. BANDUNG\n', 12);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (143, 'KAB. GARUT\n', 12);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (144, 'KAB. TASIKMALAYA\n', 12);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (145, 'KAB. CIAMIS\n', 12);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (146, 'KAB. KUNINGAN\n', 12);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (147, 'KAB. CIREBON\n', 12);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (148, 'KAB. MAJALENGKA\n', 12);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (149, 'KAB. SUMEDANG\n', 12);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (150, 'KAB. INDRAMAYU\n', 12);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (151, 'KAB. SUBANG\n', 12);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (152, 'KAB. PURWAKARTA\n', 12);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (153, 'KAB. KARAWANG\n', 12);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (154, 'KAB. BEKASI\n', 12);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (155, 'KOTA BOGOR\n', 12);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (156, 'KOTA SUKABUMI\n', 12);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (157, 'KOTA BANDUNG\n', 12);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (158, 'KOTA CIREBON\n', 12);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (159, 'KOTA BEKASI\n', 12);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (160, 'KOTA DEPOK\n', 12);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (161, 'KOTA CIMAHI\n', 12);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (162, 'KOTA TASIKMALAYA\n', 12);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (163, 'KOTA BANJAR\n', 12);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (164, 'KAB. CILACAP\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (165, 'KAB. BANYUMAS\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (166, 'KAB. PURBALINGGA\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (167, 'KAB. BANJARNEGARA\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (168, 'KAB. KEBUMEN\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (169, 'KAB. PURWOREJO\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (170, 'KAB. WONOSOBO\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (171, 'KAB. MAGELANG\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (172, 'KAB. BOYOLALI\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (173, 'KAB. KLATEN\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (174, 'KAB. SUKOHARJO\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (175, 'KAB. WONOGIRI\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (176, 'KAB. KARANGANYAR\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (177, 'KAB. SRAGEN\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (178, 'KAB. GROBOGAN\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (179, 'KAB. BLORA\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (180, 'KAB. REMBANG\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (181, 'KAB. PATI\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (182, 'KAB. KUDUS\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (183, 'KAB. JEPARA\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (184, 'KAB. DEMAK\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (185, 'KAB. SEMARANG\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (186, 'KAB. TEMANGGUNG\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (187, 'KAB. KENDAL\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (188, 'KAB. BATANG\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (189, 'KAB. PEKALONGAN\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (190, 'KAB. PEMALANG\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (191, 'KAB. TEGAL\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (192, 'KAB. BREBES\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (193, 'KOTA MAGELANG\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (194, 'KOTA SURAKARTA\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (195, 'KOTA SALATIGA\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (196, 'KOTA SEMARANG\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (197, 'KOTA PEKALONGAN\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (198, 'KOTA TEGAL\n', 13);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (199, 'KAB. KULON PROGO\n', 14);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (200, 'KAB. BANTUL\n', 14);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (201, 'KAB. GUNUNG KIDUL\n', 14);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (202, 'KAB. SLEMAN\n', 14);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (203, 'KOTA YOGYAKARTA\n', 14);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (204, 'KAB. PACITAN\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (205, 'KAB. PONOROGO\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (206, 'KAB. TRENGGALEK\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (207, 'KAB. TULUNGAGUNG\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (208, 'KAB. BLITAR\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (209, 'KAB. KEDIRI\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (210, 'KAB. MALANG\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (211, 'KAB. LUMAJANG\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (212, 'KAB. JEMBER\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (213, 'KAB. BANYUWANGI\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (214, 'KAB. BONDOWOSO\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (215, 'KAB. SITUBONDO\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (216, 'KAB. PROBOLINGGO\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (217, 'KAB. PASURUAN\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (218, 'KAB. SIDOARJO\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (219, 'KAB. MOJOKERTO\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (220, 'KAB. JOMBANG\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (221, 'KAB. NGANJUK\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (222, 'KAB. MADIUN\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (223, 'KAB. MAGETAN\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (224, 'KAB. NGAWI\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (225, 'KAB. BOJONEGORO\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (226, 'KAB. TUBAN\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (227, 'KAB. LAMONGAN\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (228, 'KAB. GRESIK\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (229, 'KAB. BANGKALAN\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (230, 'KAB. SAMPANG\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (231, 'KAB. PAMEKASAN\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (232, 'KAB. SUMENEP\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (233, 'KOTA KEDIRI\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (234, 'KOTA BLITAR\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (235, 'KOTA MALANG\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (236, 'KOTA PROBOLINGGO\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (237, 'KOTA PASURUAN\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (238, 'KOTA MOJOKERTO\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (239, 'KOTA MADIUN\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (240, 'KOTA SURABAYA\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (241, 'BATU\n', 15);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (242, 'KAB. PANDEGLANG\n', 16);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (243, 'KAB. LEBAK\n', 16);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (244, 'KAB. TANGERANG\n', 16);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (245, 'KAB. SERANG\n', 16);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (246, 'KOTA TANGERANG\n', 16);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (247, 'KOTA CILEGON\n', 16);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (248, 'KAB. JEMBARANA\n', 17);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (249, 'KAB. TABANAN\n', 17);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (250, 'KAB. BADUNG\n', 17);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (251, 'KAB. GIANYAR\n', 17);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (252, 'KAB. KLUNGKUNG\n', 17);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (253, 'KAB. BANGLI\n', 17);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (254, 'KAB. KARANGASEM\n', 17);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (255, 'KAB. BULELENG\n', 17);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (256, 'KOTA DENPASAR\n', 17);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (257, 'KAB. LOMBOK BARAT\n', 18);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (258, 'KAB. LOMBOK TENGAH\n', 18);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (259, 'KAB. LOMBOK TIMUR\n', 18);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (260, 'KAB. SUMBAWA *)\n', 18);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (261, 'KAB. DOMPU\n', 18);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (262, 'KAB. BIMA\n', 18);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (263, 'KAB. SUMBAWA BARAT*)\n', 18);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (264, 'KOTA MATARAM\n', 18);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (265, 'KOTA BIMA\n', 18);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (266, 'KAB. KUPANG\n', 19);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (267, 'KAB. TIMOR TENGAH SELATAN', 19);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (268, 'KAB. TIMOR TENGAH UTARA\n', 19);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (269, 'KAB. BELU\n', 19);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (270, 'KAB. ALOR\n', 19);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (271, 'KAB. FLORES TIMUR\n', 19);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (272, 'KAB. SIKKA\n', 19);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (273, 'KAB. ENDE\n', 19);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (274, 'KAB. NGADA\n', 19);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (275, 'KAB. MANGGARAI\n', 19);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (276, 'KAB. SUMBA TIMUR\n', 19);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (277, 'KAB. SUMBA BARAT\n', 19);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (278, 'KAB. LEMBATA\n', 19);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (279, 'KAB. ROTE NDAO\n', 19);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (280, 'KAB. MANGGARAI BARAT\n', 19);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (281, 'KOTA KUPANG\n', 19);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (282, 'KAB. SAMBAS\n', 20);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (283, 'KAB. PONTIANAK\n', 20);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (284, 'KAB. SANGGAU *)\n', 20);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (285, 'KAB. KETAPANG\n', 20);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (286, 'KAB. SINTANG *)\n', 20);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (287, 'KAB. KAPUAS HULU\n', 20);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (288, 'KAB. BENGKAYANG\n', 20);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (289, 'KAB. LANDAK\n', 20);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (290, 'KAB. MELAWI *)\n', 20);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (291, 'KAB. SEKADAU *)\n', 20);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (292, 'KOTA PONTIANAK\n', 20);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (293, 'KOTA SINGKAWANG\n', 20);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (294, 'KAB. KOTAWARINGIN BARAT\n', 21);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (295, 'KAB. KOTAWARINGIN TIMUR\n', 21);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (296, 'KAB. KAPUAS\n', 21);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (297, 'KAB. BARITO SELATAN\n', 21);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (298, 'KAB. BARITO UTARA\n', 21);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (299, 'KAB. KATINGIN\n', 21);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (300, 'KAB. SERUYAN\n', 21);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (301, 'KAB. SUKAMARA\n', 21);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (302, 'KAB. LAMANDAU\n', 21);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (303, 'KAB. GUNUNG MAS\n', 21);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (304, 'KAB. PULANG PISAU\n', 21);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (305, 'KAB. MURUNG RAYA\n', 21);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (306, 'KAB. BARITO TIMUR\n', 21);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (307, 'KOTA PALANGKARAYA\n', 21);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (308, 'KAB. TANAH LAUT\n', 22);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (309, 'KAB. KOTABARU\n', 22);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (310, 'KAB. BANJAR\n', 22);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (311, 'KAB. BARITO KUALA\n', 22);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (312, 'KAB. TAPIN\n', 22);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (313, 'KAB. HULU SUNGAI SELATAN\n', 22);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (314, 'KAB. HULU SUNGAI TENGAH\n', 22);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (315, 'KAB. HULU SUNGAI UTARA\n', 22);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (316, 'KAB. TABALONG\n', 22);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (317, 'KAB. TANAH BAMBU\n', 22);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (318, 'KAB. BALANGAN\n', 22);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (319, 'KOTA BANJARMASIN\n', 22);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (320, 'KOTA BANJARBARU\n', 22);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (321, 'KAB. PASIR\n', 23);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (322, 'KAB. KUTAI KERTANEGARA\n', 23);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (323, 'KAB. BERAU\n', 23);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (324, 'KAB. BULUNGAN\n', 23);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (325, 'KAB. NUNUKAN\n', 23);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (326, 'KAB. MALINAU\n', 23);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (327, 'KAB. KUTAI BARAT\n', 23);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (328, 'KAB. KUTAI TIMUR\n', 23);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (329, 'KAB. PENAJAM PASER UTARA\n', 23);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (330, 'KOTA BALIKPAPAN\n', 23);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (331, 'KOTA SAMARINDA\n', 23);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (332, 'KOTA TARAKAN\n', 23);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (333, 'KOTA BONTANG\n', 23);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (334, 'KAB. BOLAANG MANGONDOW\n', 24);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (335, 'KAB. MINAHASA *)\n', 24);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (336, 'KAB. KEPULAUAN SANGIHE\n', 24);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (337, 'KAB. KEPULAUAN TALAUD\n', 24);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (338, 'KAB. MINAHASA SELATAN\n', 24);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (339, 'KAB. MINAHASA UTARA*)\n', 24);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (340, 'KOTA MANADO\n', 24);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (341, 'KOTA BITUNG\n', 24);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (342, 'KOTA TOMOHON\n', 24);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (343, 'KAB. BANGGAI\n', 25);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (344, 'KAB. POSO *)\n', 25);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (345, 'KAB. DONGGALA\n', 25);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (346, 'KAB. TOLOI TOLI\n', 25);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (347, 'KAB. BUOL\n', 25);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (348, 'KAB. MOROWALI\n', 25);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (349, 'KAB. BANGGAI KEPULAUAN\n', 25);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (350, 'KAB. PARIGI MOUTONG\n', 25);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (351, 'KAB. TOJO UNA UNA*)\n', 25);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (352, 'KOTA PALU\n', 25);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (353, 'KAB. SELAYAR\n', 26);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (354, 'KAB. BULUKUMBA\n', 26);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (355, 'KAB. BANTAENG\n', 26);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (356, 'KAB. JENEPONTO.\n', 26);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (357, 'KAB. TAKALAR\n', 26);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (358, 'KAB. GOWA\n', 26);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (359, 'KAB. SINJAI\n', 26);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (360, 'KAB. BONE\n', 26);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (361, 'KAB. MAROS\n', 26);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (362, 'KAB. PANGKAJENE KEP.\n', 26);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (363, 'KAB. BARRU\n', 26);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (364, 'KAB. SOPPENG\n', 26);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (365, 'KAB. WAJO\n', 26);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (366, 'KAB. SIDENRENG RAPANG\n', 26);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (367, 'KAB. PINRANG\n', 26);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (368, 'KAB. ENREKANG\n', 26);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (369, 'KAB. LUWU\n', 26);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (370, 'KAB. TANA TORAJA\n', 26);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (371, 'KAB. LUWU UTARA\n', 26);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (372, 'KAB. LUWU TIMUR\n', 26);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (373, 'KOTA MAKASAR\n', 26);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (374, 'KOTA PARE PARE\n', 26);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (375, 'KOTA PALOPO\n', 26);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (376, 'KAB. KOLAKA*)\n', 27);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (377, 'KAB. KONAWE\n', 27);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (378, 'KAB. MUNA\n', 27);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (379, 'KAB. BUTON*)\n', 27);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (380, 'KAB. KONAWE SELATAN\n', 27);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (381, 'KAB. BOMBANA*)\n', 27);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (382, 'KAB. WAKATOBI*)\n', 27);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (383, 'KAB. KOLAKA UTARA*)\n', 27);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (384, 'KOTA KENDARI\n', 27);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (385, 'KOTA BAU BAU\n', 27);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (386, 'KAB. GORONTALO\n', 28);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (387, 'KAB. BOALEMO\n', 28);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (388, 'KAB. BONE BOLANGO\n', 28);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (389, 'KAB. PAHUWATO\n', 28);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (390, 'KOTA GORONTALO\n', 28);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (391, 'KAB. MAMUJU UTARA\n', 29);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (392, 'KAB. MAMUJU\n', 29);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (393, 'KAB. MAMASA\n', 29);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (394, 'KAB. POLOWALI MAMASA\n', 29);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (395, 'KAB. MAJENE\n', 29);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (396, 'KAB. MALUKU TENGAH *)\n', 30);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (397, 'KAB. MALUKU TENGGARA *)\n', 30);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (398, 'KAB. MALUKU TENGGARA BRT\n', 30);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (399, 'KAB. BURU\n', 30);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (400, 'KAB. SERAM BAGIAN TIMUR*)', 30);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (401, 'KAB. SERAM BAGIAN BARAT *', 30);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (402, 'KAB. KEPULAUAN ARU*)\n', 30);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (403, 'KOTA AMBON\n', 30);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (404, 'KAB. HALMAHERA BARAT\n', 31);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (405, 'KAB. HALMAHERA TENGAH\n', 31);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (406, 'KAB. HALMAHERA UTARA\n', 31);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (407, 'KAB. HALMAHERA SELATAN\n', 31);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (408, 'KAB. KEPULAUAN SULA\n', 31);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (409, 'KAB. HALMAHERA TIMUR\n', 31);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (410, 'KOTA TERNATE\n', 31);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (411, 'KOTA TIDORE KEPULAUAN\n', 31);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (412, 'KAB. MERAUKE\n', 32);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (413, 'KAB. JAYAWIJAYA\n', 32);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (414, 'KAB. JAYAPURA\n', 32);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (415, 'KAB. NABIRE\n', 32);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (416, 'KAB. YAPEN WAROPEN\n', 32);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (417, 'KAB. BIAK NUMFOR*)\n', 32);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (418, 'KAB. PUNCAK JAYA\n', 32);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (419, 'KAB. PANIAI\n', 32);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (420, 'KAB. MIMIKA\n', 32);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (421, 'KAB. SARMI\n', 32);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (422, 'KAB. KEEROM\n', 32);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (423, 'KAB. PEGUNUNGAN BINTANG\n', 32);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (424, 'KAB. YAHUKIMO\n', 32);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (425, 'KAB. TOLIKARA\n', 32);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (426, 'KAB. WAROPEN\n', 32);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (427, 'KAB. BOVEN DIGOEL\n', 32);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (428, 'KABUPATEN. MAPPI\n', 32);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (429, 'KAB. ASMAT\n', 32);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (430, 'KAB. SUPIORI*)\n', 32);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (431, 'KOTA JAYAPURA\n', 32);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (432, 'KAB. SORONG\n', 33);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (433, 'KAB. MANOKWARI\n', 33);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (434, 'KAB. FAK FAK\n', 33);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (435, 'KAB. SORONG SELATAN\n', 33);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (436, 'KAB. RAJA AMPAT\n', 33);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (437, 'KAB. TELUK BENTUNI\n', 33);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (438, 'KAB. TELUK WONDAMA\n', 33);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (439, 'KAB. KAIMA\n', 33);
INSERT INTO `kota` (`idkota`, `kota`, `idprovinsi`) VALUES (440, 'KOTA SORONG\n', 33);
