INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (1, 'NANGGROE ACEH D');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (2, 'SUMATERA UTARA');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (3, 'SUMATERA BARAT');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (4, 'RIAU');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (5, 'JAMBI');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (6, 'SUMATERA SELATA');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (7, 'BENGKULU');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (8, 'LAMPUNG');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (9, 'KEP BANGKA BELI');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (10, 'KEP RIAU');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (11, 'DKI JAKARTA');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (12, 'JAWA BARAT');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (13, 'JAWA TENGAH');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (14, 'DI JOGJAKARTA');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (15, 'JAWA TIMUR');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (16, 'BANTEN');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (17, 'BALI');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (18, 'NUSA TENGGARA B');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (19, 'NUSA TENGGARA T');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (20, 'KALIMANTAN BARA');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (21, 'KALIMANTAN TENG');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (22, 'KALIMANTA SELAT');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (23, 'KALIMANTAN TIMU');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (24, 'SULAWESI UTARA');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (25, 'SULAWESI TENGAH');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (26, 'SULAWESI SELATA');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (27, 'SULAWESI TENGGA');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (28, 'GORONTALO     ');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (29, 'SULAWESI BARAT');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (30, 'MALUKU');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (31, 'MALUKU UTARA');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (32, 'PAPUA');
INSERT INTO `provinsi` (`idprovinsi`, `provinsi`) VALUES (33, 'PAPUA BARAT (PP');
